// Types for InversifyJS dependency injection

export const TYPES = {
    // Controllers
    UserController: Symbol.for('UserController'),
    AuthController: Symbol.for('AuthController'),
    OfferController: Symbol.for('OfferController'),
    DineInController: Symbol.for('DineInController'),
    PaymentController: Symbol.for('PaymentController'),
    ReviewController: Symbol.for('ReviewController'),
    FeedbackController: Symbol.for('FeedbackController'),
    AdminController: Symbol.for('AdminController'),
    SuperAdminController: Symbol.for('SuperAdminController'),
    OutletController: Symbol.for('OutletController'),
    StaffController: Symbol.for('StaffController'),
    OutletAdminController: Symbol.for('OutletAdminController'),
    EventController: Symbol.for('EventController'),
    EventAuthController: Symbol.for('EventAuthController'),
    EventManagerController: Symbol.for('EventManagerController'),
    EventStaffController: Symbol.for('EventStaffController'),
    TicketTierController: Symbol.for('TicketTierController'),
    OrderController: Symbol.for('OrderController'),
    TicketController: Symbol.for('TicketController'),
    HealthController: Symbol.for('HealthController'),
    
    // Services
    UserService: Symbol.for('UserService'),
    AuthService: Symbol.for('AuthService'),
    OfferService: Symbol.for('OfferService'),
    DineInService: Symbol.for('DineInService'),
    PaymentService: Symbol.for('PaymentService'),
    ReviewService: Symbol.for('ReviewService'),
    FeedbackService: Symbol.for('FeedbackService'),
    AdminService: Symbol.for('AdminService'),
    SuperAdminService: Symbol.for('SuperAdminService'),
    OutletService: Symbol.for('OutletService'),
    StaffService: Symbol.for('StaffService'),
    OutletAdminService: Symbol.for('OutletAdminService'),
    EventService: Symbol.for('EventService'),
    EventAuthService: Symbol.for('EventAuthService'),
    EventManagerService: Symbol.for('EventManagerService'),
    EventStaffService: Symbol.for('EventStaffService'),
    TicketTierService: Symbol.for('TicketTierService'),
    OrderService: Symbol.for('OrderService'),
    TicketService: Symbol.for('TicketService'),
    SendGridService: Symbol.for('SendGridService'),
    RewardService: Symbol.for('RewardService'),
    
    // Repositories
    UserRepository: Symbol.for('UserRepository'),
    AdminRepository: Symbol.for('AdminRepository'),
    OfferRepository: Symbol.for('OfferRepository'),
    DineInSessionRepository: Symbol.for('DineInSessionRepository'),
    PaymentRepository: Symbol.for('PaymentRepository'),
    ReviewRepository: Symbol.for('ReviewRepository'),
    FeedbackRepository: Symbol.for('FeedbackRepository'),
    OutletRepository: Symbol.for('OutletRepository'),
    StaffRepository: Symbol.for('StaffRepository'),
    EventRepository: Symbol.for('EventRepository'),
    TicketTierRepository: Symbol.for('TicketTierRepository'),
    OrderRepository: Symbol.for('OrderRepository'),
    TicketRepository: Symbol.for('TicketRepository'),
};